// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type User struct {
	Id               int64     `json:"Id"`
	Username         string    `json:"Username"`
	Password         string    `json:"Password"`
	FirstName        string    `json:"FirstName"`
	LastName         string    `json:"LastName"`
	Email            string    `json:"Email"`
	PasswordAtChange time.Time `json:"Password_At_Change"`
	CreatedAt        time.Time `json:"Created_At"`
}
